# Define el compilador a usar, gcc
GCC = gcc
# Define la bandera de compilacion, libreria matematica
CFLAGS = -lm
# Define las banderas para usar OpenMP
# -fopenmp habilita OpenMP, -O3 activa optimizaciones de alto nivel
FOPENMP = -fopenmp -O3
# Define la librería POSIX para manejo de hilos, pthread
POSIX = -lpthread

# Nombre del archivo fuente que se va a compilar
modulo = inter.c
# Define el programas que se van a generar con el Makefile, mmClasicaOpen MP
PROGRAMAS = mmClasicaOpenMP 

# Compila todos los programas definidos en PROGRAMAS
ALL: $(PROGRAMAS)

# Compila el archivo mmClasicaOpenMP.c, lo enlaza con OpenMP y genera el ejecutable
mmClasicaOpenMP:
	$(GCC) $(CLFAGS) $@.c -o $@ $(FOPENMP)

# Limpia el directorio
# Elimina los ejecutables listados en PROGRAMAS
clean:
	$(RM) $(PROGRAMAS) 
